name: Build Test

on:
  push:
    branches: [dev]

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies and build server
        working-directory: ./server
        run: |
          bun install 
          bun run test
          bun run build

      - name: Upload server artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: server/dist/

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build web
        working-directory: ./web
        run: |
          npm install
          npm run build

      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: web/dist/

  build-web-builder:
    name: Build Web Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies and build web
        working-directory: ./web-builder
        run: |
          bun install
          bun run build

      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-builder
          path: web-builder/dist/