name: Build Release

on:
  push:
    branches: [main]

env:
  COMMIT_HASH: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write 

jobs:
  server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies and build server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./server
        run: |
          bun install 
          bun run test
          bun run build
          bun run release

  web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies and build web
        working-directory: ./web
        run: |
          bun install
          bun run type-check
          bun run build:config
          bun run release

  web-builder:
    name: Build Web Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies and build web
        working-directory: ./web-builder
        run: |
          bun install 
          bun run build
          bun run release